### ISSUE TITLE
Adding a `CRLF` in a message box string

### ISSUE THREAD

**Issue by Gitoffthelawn** [d0vgan/nppexec#32] opened 2021-03-16 00:21 UTC
I'm not sure if there is a way to add a `CRLF` in a message box string.  Is that possible?  If not, could it be made possible?

**Comment by d0vgan** [comment] 2021-03-16 14:52
Here is what comes to my mind regarding multi-line strings:
```
set local msg ~ strfromhex "Message Line 1" 0A 00 "Message Line 2"
```
We are using two bytes 0A 00 because we are dealing with a Unicode (UCS-2) string where each character is represented by two bytes. The byte order is Little Endian, which means the lower byte goes first, the higher byte goes second.
That is why:
\r = 0D 00
\n = 0A 00

**Comment by artie-finkelstein** [comment] 2021-06-21 05:09
Using Npp 8.1 this seems to work only if the message lines (segments) are short.  If line one is too long, line two is truncated, likewise the shorter line 1 is the longer line 2 can be.  Some additional experiments with 2, 4 & 6 message segments, with up to 50 characters per segment generally resulted in only the last segment being truncated.  Oddly enough, longer initial segments often showed the truncation later in the last segment.  I'm sorry this report isn't more specific, I'm still trying to get a handle on input .vs. output to create a definitive test case.  So far I can reproduce the problem in the console with the following code fragment:

```
set local msg1 = "99999123456789012345678901234567890123456789099999"
set local msg2 = "55555123456789012345678901234567890123456789055555"
set local msg3 = "12345678901234567890"
set local msga1 = "abcdefghijklmnopqrstuvwxyz"
set local msga2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
set local msga3 = "zyxwvutsrqponmlkjihgfedcba"
set local msg ~ strfromhex $(msg1) 0A 00 $(msga1) 
echo -- 1 & a1 --
echo $(msg)
set local msg ~ strfromhex $(msg1) 0A 00 $(msga1) 0A 00 $(msg2) 0A 00 $(msga2) 
echo -- 1 & a1 & 2 & a2 --
echo $(msg)
set local msg ~ strfromhex $(msg1) 0A 00 $(msga1) 0A 00 $(msg2) 0A 00 $(msga2) 0A 00 $(msg3) 0A 00 $(msga3)
echo -- 1 & a1 & 2 & a2 & 3 & a3 --
echo $(msg)
```
The truncation problem was initially noticed with following messagebox code when using the 2021.06.20 test release:
```
set local msg ~ strfromhex "command '$(INPUT)' is not available from the interactive menu," 0A 00 "use the NppExec console" 
messagebox $(msg) : "Warning" : : 10000
```
But truncation also occurs in the console with the 0.62 release dated: 2021.02.25

Additionally, the single quotes around $(INPUT) are filtered out when using the 'strfromhex' approach, but are left intact if I use the traditional single text field approach.  To me this is less of an issue than the unexpected truncation of the message segments.

**Comment by d0vgan** [comment] 2021-06-21 13:18
The trucated text was caused by a mistake in NppExec's internal method calcStrFromHex().
Please find the fixed version NppExec20210621_dll_PA.zip here:
https://sourceforge.net/projects/npp-plugins/files/NppExec/NppExec%20Plugin%20%28dev%29/

As for disappeared single quotes, just add another pair of quotes around the $(msg):
```
messagebox "$(msg)" : "Warning" : : 10000
```
or
```
messagebox `$(msg)` : "Warning" : : 10000
```
More on this in NppExec's Manual, section 3.8.5. Passing enquoted strings and special characters.

**Comment by artie-finkelstein** [comment] 2021-06-21 18:10
The fixed 'strfromhex' works wonderfully.

The double quoting of the 'merged' multi-line string variable also
works as desired; double quoting on the individual segments does not
preserve the inner single quotes on the subsequent messagebox
invocation, my mistake (I need to remind myself NppExec is a script
interpreter, not a script compiler/executor).

Thank you for the fast response.

**Closed** 2021-08-16 08:28 UTC

**Comment by artie-finkelstein** [comment] 2021-08-16 17:05
I had just completed work on a simple formatted message box function and was looking through my notes to find a URL to use to thank you for the original 'strfromhex' idea.  Once again it works great.  Thank you.
