### ISSUE TITLE
Be ready for the new Plugin Admin

### ISSUE THREAD

**Issue by d0vgan** [d0vgan/nppexec#8] opened 2018-10-30 20:17 UTC
There is the ongoing discussion in the Notepad++ community forum about the newly introduced Npp Plugin Admin, see here:
https://notepad-plus-plus.org/community/topic/16494/new-built-in-plugin-admin-plugin-manager-is-ready
Further infos are obtainable here:
https://notepad-plus-plus.org/features/plugin-admin.html

See also:
https://sourceforge.net/p/npp-plugins/discussion/672146/thread/32508d88ef/

**Comment by chcg** [comment] 2018-11-24 11:49
Don't you want to host the source of https://sourceforge.net/projects/npp-plugins/files/XBrackets%20Lite/ https://sourceforge.net/projects/tagsview/files/TagsView%20for%20Notepad%2B%2B/ which seems to be also your plugins also here on github?

**Comment by d0vgan** [comment] 2018-11-30 10:07
@chcg,
This can be done - though I I'm not sure what benifit it would bring. XBrackets Lite is small and specific, it is not actively developed. TagsView still waits until I update it to newer (and better) versions of ctags and Win32++. What is specific to TagsView is its cross-editor orientation (currently 2 editors are supported) and I don't want changes that would break that.

**Comment by chcg** [comment] 2018-12-01 09:47
Maybe someone likes\needs just this specific feature and if it is part of the pluginAdmin it might be found easier. And some guy could contribute easier if the source is available here I think.
Or other plugin authors could get some ideas from your code or take it as starting point for own extensions.

**Comment by vinsworldcom** [comment] 2019-08-20 14:14
I might be hijacking this thread, but I use TagsView for N++ 7.7.1 64-bit and it works great.  I used to use [SourceCookifier](https://sourceforge.net/projects/sourcecookifier/), but with no 64-bit version of that, I discovered TagsView and it [compiled for me](https://github.com/vinsworldcom/nppTagsView).  

I especially like that it respects my $HOME/.ctags file thus automatically adds new tags and languages in the dockable view that I define in that .ctags config file.

The only enhancement I'd like to see is a way to show all tags of all open files in the dockable instead of just the tags of the current file.  I've been hacking at the source to try and get that to happen, but I'm not nearly as talented with C++.

I hope you do decide to move it from SourceForge to GitHub and keep it available for Notepad++.  Thanks again for NppExec too - without which I simply couldn't use Notepad++ I have so much automation built with NppExec!

Cheers.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-10-07 19:53
Не логичнее было бы добавить возможность сохранения/использования сторонней директории для файла конфигурации (я конкретно об npes_saved.txt и тп.), раз у нас уже есть 'Облачное хранилище' в npp?

![](https://i.imgur.com/KTQTyRE.png)


Ну и конечно же добавить возможность использовать ctrl (+alt/+shift) + key, чтобы можно было настроить на общий лад со студией, где нажатие ctrl + f5/f6 запускает различные методы.

@d0vgan

**Comment by d0vgan** [comment] 2020-10-08 13:25
@afwn90cj93201nixr2e1re 
As for Cloud settings, I am not sure if it is available to plugins (e.g. I can't find neither "cloud" nor "setting" inside the 'Notepad_plus_msgs.h')

As for the shortcut keys, is already possible via the Shortcut Mapper:
![](https://i.imgur.com/Edx3tV3.png)

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-11-15 01:53
Could you ask them to provide cloud config path to api? Coz it's really useful.
@d0vgan

**Comment by chcg** [comment] 2020-11-16 05:35
@d0vgan The zips of release https://github.com/d0vgan/nppexec/releases/tag/v061 are not in a format which could be used by PluginAdmin because the nppexec.dll is not in the top dir of the zip, but in a extra nppexec folder. Could you please correct that by removal of the nppexec folder.

**Comment by d0vgan** [comment] 2020-11-16 11:09
@chcg
I've updated the v061 release with zip-archives with "classic" folder structure.
Though it's kind of ironic that the PluginAdmin does not understand the folder structure that has been presented together with the PluginAdmin itself :)

**Comment by chcg** [comment] 2020-11-20 18:19
Added v061 with https://github.com/notepad-plus-plus/nppPluginList/commit/2bf0c1832f48ea08fa71d23eeb758b618a5bb0ae. I think the structure of the zip changed from the first PA version to the first released one.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-12-21 15:20
@d0vgan 

![изображение](https://user-images.githubusercontent.com/9306996/102792056-d48fff80-439f-11eb-8ccf-09e103deb43a.png)


Today at about 5 am I closed notepad and other programs, then shutdowned pc, now it's turned out that the file is corrupted. There is definitely no fclose lost anywhere? I mean how is that possible?

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-12-21 15:24
Also, could you compile develop branch too? I mean just make it as pre-release if it's done.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-12-21 23:11
Ok, i know how to reproduce it, just close notepad with openned script window right before powering off the PC, i mean just make backups at first, open notepad, open execute window start to edit it press power button (or just turn off electricity) and right before shutdown instantly close notepad thru close button, notepad will start close all threads and probably your plugin will make backup or idk, save itself to disk (probably fflush forgotten somewhere) and after booting you will get corrupted script file.

So, probably you don't need to close notepad instantly  before shutdown, because i closed it before few seconds, about 10-15 seconds before pressed shutdown button (i know i shouldn't, but 15 seconds... It's should be pretty enough?).

**Comment by d0vgan** [comment] 2020-12-22 09:12
These are interesting findings, but how are they related to the Plugin Admin?
Please create a new issue (e.g. "Saved script becomes corrupted on shutdown") and move this info there.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-12-22 10:19
I don't really want, so, that's why im just writing here. File corruption is expected due specific on file operations (reading, writing, seeking, flushing), so, i mean probably not of all mine programs have tgis issue, for example npp itself had this issue in past, visual studio also had, but they fixed it somehow.

https://stackoverflow.com/a/24302389/13453323

Probably could help u, i mean im pretty not sure why is that happening, but, i guess it's due late fflush'ing on disk.

**Comment by d0vgan** [comment] 2022-02-12 19:03
XBrackets Lite is now hosted on github! It's better late than never :)
https://github.com/d0vgan/npp-XBracketsLite

**Comment by chcg** [comment] 2022-03-05 19:00
@d0vgan This issue could be closed as nppexec is available via PluginAdmin. Just updated to v0.8.0 with https://github.com/notepad-plus-plus/nppPluginList/commit/db50416f13272c8df18b86c88e7a0ca5ac2c2ba5 and XBracketsLite with https://github.com/notepad-plus-plus/nppPluginList/commit/f1dee6231f0eb15ab732ee5c31d235cba021c0d5

**Closed** 2022-03-05 19:27 UTC
Labels: enhancement
